### ISSUE TITLE
Current.php, 5day.php.

### ISSUE THREAD

**Issue by IB4650** [peterkvt80/makenews#2]
1. As of 2 weeks ago, Current.php no longer gets the time data to from the met office website to give                                weather report for the cities of the UK. as it gives an error on line 36. 

2. 5day.php shows that there is no header.php file included. The header.php is not in the
    makenews listing.

**Comment by avrovulcanxh607** [comment]
Hi,
I noticed the problem with current.php, but haven't had time to look at it yet, I'll take a look tonight.
5day.php shouldn't be including header.php, that's an internal script I use for debugging. I'll remove that asap.
Sorry you're having problems!

**Comment by avrovulcanxh607** [comment]
35ab35df53d01fcec4b30cd2790cfd0c897a5bcd should fix your problem. For some reason this page only has yesterday's data, which was causing problems. I've added a fallback to yesterday's data in the event that today's isn't available.

**Comment by IB4650** [comment]
Hi,

  Thank you very much for your help in getting Current.php working again. In addition when I spotted that you removed the header.php  from 5day.php 

 I now can get the 5 day weather forecast as well. The new weather map file works as well when I remove the header file script from it.

 Sorry that I did not get the chance to email you back sooner.

 

Regards,

   Ian.

**Comment by avrovulcanxh607** [comment]
Hi,
You might be interested in [Makeceefax](https://github.com/nat2001/makeceefax), it's not finished yet but eventually it should have all the features available here and more. It should also be quicker to execute.

**Comment by IB4650** [comment]
Hi Nathan,
    Thank you very much for letting me know about the new make Ceefax Service.  I am also having problems with the weather Current.php file again only giving 4 Cities from Aberdeen to Birmingham weather reports. It reports an error on Line 41 which may be due to the time module.

Regards,
  Ian.

**Comment by avrovulcanxh607** [comment]
It's a pain. I really need to add some kind of pass-through so that if a page fails, it just misses it out. Pages like current.php that load lots of webpages have a habit of failing

**Comment by IB4650** [comment]
Hi Nathan,

 

   Would it be possible whether you could develop a Sports News Section so that it gives up to date Premier League Tables and Football Team news. I currently use the make news files to get the latest football news by changing the RSS Feed to BBC Sport/Football to capture the files from the BBC website but it is patchy; the news index does not work properly and I get the “ Missing Introduction Error” within the title but I still get some pages that do work and I add them to the Sports section I

have created on my Version of Teefax.

 

I look forward to your reply,

 

Regards,

   Ian.

**Comment by avrovulcanxh607** [comment]
I've actually already been toying with that - I just never released it. I'll put them up, but they might be a bit buggy. Hopefully there'll be a module for makenews for sport eventually.

**Comment by IB4650** [comment]
Thank you very much for your help. I look forward to hearing from you soon.

 

Regards,

 Ian.

**Comment by avrovulcanxh607** [comment]
Hi, I know this isn't really the right place to discuss this but I've no other way of contacting you. If you're not already using [Makeceefax](https://github.com/nat2001/makeceefax), I just added support for football League tables. If you take a look I'd appreciate feedback. Thanks

**Comment by IB4650** [comment]
Hi Nathan,
   I do use make Ceefax and I also combine it with the old makenews as well. I will take a look at the weekend at the football tables. I also managed to get Current.php working by striking out Bristol and replacing it with Bedford which is close to my area. The weather map has stopped working in the make news section as the met office has changed. Could you please update Weather in this section. I use my PC to make my Ceefax pages and then transfer them to my Raspberry pi.

Regards,
Ian.

**Comment by avrovulcanxh607** [comment]
Makeceefax is a new system that does all the old functions as well as some new ones, so you won't need to continue using the old makenews system. Setup instructions for makeceefax can be found [here](https://github.com/nat2001/makeceefax/wiki/Setup).

**Comment by IB4650** [comment]
Hi Nathan,
   The new layout of makeceefax is great but I am having problems of getting the Weather to work. I signed up to the Met Office site to get my api key, l created a file called api.php, followed instructions on pasting the key into “key goes here” and still does not work. I am using my Raspberry Pi to create the ceefax pages.
 I look forward to your reply.
Regards,
Ian.

**Comment by avrovulcanxh607** [comment]
Does it give any error messages?

**Comment by IB4650** [comment]
Hi,
  The Error message is “home/pi/ceefax/AUTO401.tti failed to open stream.

Regards,
Ian.

**Comment by avrovulcanxh607** [comment]
Have you the /home/pi/ceefax folder created and given it the appropriate permissions? If you don't want to use this folder you need to change PAGEDIR in makeceefax.php. PHP gives this error when it tries to write to a folder that doesn't exist or it hasn't permission to do so.
If the folder is created, try running "sudo chmod 777 /home/pi/ceefax -R" and try again

**Comment by IB4650** [comment]
Hi,
   I created the directory /home/pi/ceefax, everything else but the weather works. I do not seem to know about permissions when everything else seems to work.

Ian.

**Comment by avrovulcanxh607** [comment]
Not sure what's causing it then, I'll have to do some checks

**Comment by avrovulcanxh607** [comment]
Could you give me the full error output?
I've tried this on a clean system and it seems to be working ok

**Comment by IB4650** [comment]
Hi Nathan,
   I managed to get the weather map to work but not on the Raspberry Pi at the moment. I was changing some settings in the make Weather file for PAGEDIR”, “\PAGES” , changed the makeceefax directory to PAGEDIR “,”C:\PAGES” and changed AUTO with P for pages. I then went back to make Weather file and changed require “../ common.php” to require “common.php” and copied common.php into the makeweather directory. At the moment I have only found how to make it work on my PC using XAMMP with PHP Version 5. When I get more time I will try on my Raspberry Pi again.

Regards,
Ian

**Comment by avrovulcanxh607** [comment]
The require ../common is just there so that I can run the script on it's own during testing, and is commented out, so that shouldn't make any difference. I'm still not sure what's causing this problem, maybe we should open an issue on makeceefax rather than continuing here?
